[workspace]
members = [
    "common",
    "craftlib",
    "programs/pow",
    "programs/wood",
    "programs/stone",
    "programs/axe",
]
resolver = "2"

[workspace.dependencies]
sha2 = "0.10.8"
serde = "1.0.204"
bincode = "1.3.3"
hex = "0.4.3"