[package]
name = "stone-program"
version = "1.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { version = "5.0.8", features = ["verify"] }
sha2 = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
pow-program = { path = "../pow" }